version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-axolotl-curve25519
    versions:
    - "< 0.4.2, > 0.4.1.post2"
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - "3.4"
    - 3.4.1
    - 3.4.2
    - 3.4.3
