sudo: required
services:
  - docker
language: python

env:
  global:
    - REPOSITORY=debian-p16n
    - USERNAME=praekeltfoundation
    - secure: gIwtErLvnLJjJsM6BBWi5G3vorM8WKCB03dTqovI663Kdw0UY/uscIt2zwELb7NDnFO7qxoUpk8ZlHOcbsg5Tn+C4Tn7qY/1s/MOEyI+JLB2+WnhXvUdHH8dizJJzi1lKVV2FVEjDJjZ+kwd1PWlxB0UdU+wIwOIlPfZeHgyrMIg/lLJEozNI1SuL3mvsjs5A4ZAyDmPFQB2Ec+rBknCzu5xjFEoz6EOdOC0KGLjYNeb+dcZAehEbd4BtLF8wJra3EMWUNIJcA0siOon23UcDfVYcTFfNnmaUcTsFBghVGUUsfyRKFubpSK7kimB9s55KUVjW2xkSIplosEzwKzfEPByiepy9DwTWG1QA8RIL2acrbACp25rcgJMtfH9i/uRwFfy2MPwa3rtNMdATLlKF3c+unP1PyoeL9DLKGsge9WecgUdp37C+GeddB+dS3nwMrs+b9Ck4p1y1B8pyMjmsy/VKYm/YyzIvxLRvtFYN/eCEojc56RIUbgkMKCppIlXzniW0U9e3mz67SiieMeP7qkiVvaz/JLYNOF6gHTyc6R8UkYU9sTRhbwpOKsreb3aQE8CoeNk4A7TdyZab2rIpo3pvJ9yJLCArdWfV/TvQoalMNr8hlYp00QLgJiIt5IHkVk6A9/9YaXixtuAm9mf500yPFKa+yj+UMb5kcH8Cpw=
  matrix:
    - DOCKER_IMAGE=python:2

install:
  - docker pull $DOCKER_IMAGE
  - pip install twine
script:
  - mkdir -p wheelhouse
  - ./build.sh -d $DOCKER_IMAGE

deploy:
  provider: script
  skip_cleanup: true
  script: twine upload -r $REPOSITORY -u $USERNAME -p $PASSWORD --config-file .pypirc wheelhouse/*
  on:
    branch: develop
