dist: xenial
services: docker
language: python
cache:
  directories:
    - wheelhouse

# Only build develop & master. PRs still get built.
branches:
  only:
    - develop
    - master

env:
  global:
    - TWINE_USERNAME=praekeltorg
    # TWINE_PASSWORD=<secret>
    - secure: "mkYj3fOKFymdaO2x29gFbvId1wwo3HV3+8cCCgneZXwvlRThfGjIMFSYGJAcLXsX5cudV0jvgbICGP7vZgmbEBiTFJreimO+19TLVzzgx54lR1dNkYQbVWxlUZqlI+uSW0KV6L1jj8UAIEEMOHe8zduhKqom7BkLhoAJNPIzaBxoB+unvzwqDYokzqroSLBljeqfYnRcLTdt7kM2UHrgA3Pnl5CyRSWBCUsWPbC8JE2IrXMkCxo26cDbNOb7eFIP7OP3qhH/UH5igp5X/2kHwc3xRTLAbycsd511vCHzgGfQreFcmbAljXzX0oAiuN/EJgiNhvqGTT7Kev9gB0fr0ZlaZEMhSA2fabvYgQpd0cg765KsDnCTFzTY5FZ+rRNJ5FWlHtuIGXnKPQtnq6kth7nXqmVu25FGEJnSwJgq7uugWWCr5sUFN1OHjINDvrabKbJGgLp+R93hwrnX+TsJowvB389fSEbVYq+vg/9UA9GyWV8d0YJL7ljnUX81yB+jsm2Lk+ndo8wSnqdE127nE8wYB1stdowmoHWvN1GgltG5A2KC1oDlv/7Ga1RdTQW1lMjA9z19FY4EtpnoSDgGZbK8Pztq+F/cTCO1JyzguNagrbzec6R2kxHJKn3A1ZfvnHQCgmiD113l5xnw9K8QHqhGZcScxIhsNl6CkG6mBp8="
matrix:
  include:
    # Debian Stretch/cPython 2.7
    - env:
      - DOCKER_IMAGE=python:2.7-stretch
      - TWINE_REPOSITORY=stretch
    # Debian Stretch/cPython 3.6
    - env:
      - DOCKER_IMAGE=python:3.6-stretch
      - TWINE_REPOSITORY=stretch
    # Debian Stretch/cPython 3.7
    - env:
      - DOCKER_IMAGE=python:3.7-stretch
      - TWINE_REPOSITORY=stretch

install:
  - docker pull $DOCKER_IMAGE
before_script:
  - mkdir -p wheelhouse
script:
  - ./build.sh -d $DOCKER_IMAGE

before_deploy:
  - pip install 'twine>=1.8.0'
deploy:
  provider: script
  skip_cleanup: true
  script: twine upload --skip-existing --config-file .pypirc wheelhouse/*
  on:
    branch: develop
