sudo: required
dist: trusty
services:
  - docker
language: python
cache:
  directories:
  - wheelhouse

# Only build develop & master. PRs still get built.
branches:
  only:
    - develop
    - master

env:
  global:
    - REQUIREMENT=requirements.txt
    - TWINE_USERNAME=praekeltorg
    - secure: "mkYj3fOKFymdaO2x29gFbvId1wwo3HV3+8cCCgneZXwvlRThfGjIMFSYGJAcLXsX5cudV0jvgbICGP7vZgmbEBiTFJreimO+19TLVzzgx54lR1dNkYQbVWxlUZqlI+uSW0KV6L1jj8UAIEEMOHe8zduhKqom7BkLhoAJNPIzaBxoB+unvzwqDYokzqroSLBljeqfYnRcLTdt7kM2UHrgA3Pnl5CyRSWBCUsWPbC8JE2IrXMkCxo26cDbNOb7eFIP7OP3qhH/UH5igp5X/2kHwc3xRTLAbycsd511vCHzgGfQreFcmbAljXzX0oAiuN/EJgiNhvqGTT7Kev9gB0fr0ZlaZEMhSA2fabvYgQpd0cg765KsDnCTFzTY5FZ+rRNJ5FWlHtuIGXnKPQtnq6kth7nXqmVu25FGEJnSwJgq7uugWWCr5sUFN1OHjINDvrabKbJGgLp+R93hwrnX+TsJowvB389fSEbVYq+vg/9UA9GyWV8d0YJL7ljnUX81yB+jsm2Lk+ndo8wSnqdE127nE8wYB1stdowmoHWvN1GgltG5A2KC1oDlv/7Ga1RdTQW1lMjA9z19FY4EtpnoSDgGZbK8Pztq+F/cTCO1JyzguNagrbzec6R2kxHJKn3A1ZfvnHQCgmiD113l5xnw9K8QHqhGZcScxIhsNl6CkG6mBp8="
matrix:
  include:
    # Debian Jessie/cPython 2.7
    - env:
      - DOCKER_IMAGE=python:2.7.15-jessie
      - EXTRA_REQUIREMENT=requirements-debian.txt
      - PYPI_REPO=jessie
    # Debian Jessie/cPython 3.6
    - env:
      - DOCKER_IMAGE=python:3.6.6-jessie
      - EXTRA_REQUIREMENT=requirements-debian.txt
      - PYPI_REPO=jessie
    # Debian Stretch/cPython 2.7
    - env:
      - DOCKER_IMAGE=python:2.7.15-stretch
      - EXTRA_REQUIREMENT=requirements-debian.txt
      - PYPI_REPO=stretch
    # Debian Stretch/cPython 3.6
    - env:
      - DOCKER_IMAGE=python:3.6.6-stretch
      - EXTRA_REQUIREMENT=requirements-debian.txt
      - PYPI_REPO=stretch
    # Debian Jessie/PyPy2
    - env:
      - DOCKER_IMAGE=pypy:2-6.0.0
      - EXTRA_REQUIREMENT=requirements-debian.txt
      - PYPI_REPO=jessie
    # Debian Jessie/PyPy3
    - env:
      - DOCKER_IMAGE=pypy:3-6.0.0
      - EXTRA_REQUIREMENT=requirements-debian.txt
      - PYPI_REPO=jessie
    # Alpine 3.7/cPython 2.7
    - env:
      - DOCKER_IMAGE=praekeltfoundation/alpine-python:2.7.15-alpine3.7
      - EXTRA_REQUIREMENT=requirements-alpine.txt
      - PYPI_REPO=alpine-3.7
    # Alpine 3.7/cPython 3.6
    - env:
      - DOCKER_IMAGE=praekeltfoundation/alpine-python:3.6.6-alpine3.7
      - EXTRA_REQUIREMENT=requirements-alpine.txt
      - PYPI_REPO=alpine-3.7

install:
  - docker pull $DOCKER_IMAGE
before_script:
  - mkdir -p wheelhouse
  - REQUIREMENT_OPTS="-r $(pwd)/$REQUIREMENT${EXTRA_REQUIREMENT:+ -r $(pwd)/$EXTRA_REQUIREMENT}"
script:
  - ./build.sh -d $DOCKER_IMAGE $REQUIREMENT_OPTS

before_deploy:
  - pip install 'twine>=1.8.0'
deploy:
  provider: script
  skip_cleanup: true
  script: twine upload -r "$PYPI_REPO" --skip-existing --config-file .pypirc wheelhouse/*
  on:
    branch: develop
