name: continuous integration
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  ci:
    uses: ${{ github.repository }}/.github/workflows/shared.yaml@${{ github.sha }}
