name: continuous integration
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  ci:
    uses: praekeltfoundation/debian-wheel-mirror/.github/workflows/shared.yaml@shared-workflow
